export const msgs = [
  "Haiii sebelum ituu aku mau ngucapin terima kasih dulu sama kamu, udaa mau repot - repot ngeliat sampe sini hehehehe. Anw i made these all for youu bubb <3 i hope u like it. Maaf kalau misalkan banyak yang miss yaa, entah itu dari UI nya atau fungsinya sksksk. Lovee you sayang",
  "Ohiyaa semoga kadonya kamu sukaa yaaa x.x, aku minta maaf kalau misalkan masii kurenggg atau ada hal yang anu - anu. Karena aku masi belum tauuu banget apa yang kamu sukaa :( teach me ya bub :>",
  "Selamat ulang tahun Raisya Ariana Asfriansah, sehat - sehat teruss jangan sakittttt, tetep sayang sama akuuu, makin banyakk rezekinyaaa, makinn cantikk orangnya, makin lucuu orangnya. Cieee udaaa 16 Tahunnn, tahun depan uda bisa bikin KTP tu bub HAHAHAHA.",
  "Terimakasiii yaa atas perjuangan kamu selama setahun belakangan ini. Susah senang yang udah kamu lewati, entah itu sendirian atau ada orang yang menemani kamu itu keren banget???? I'm so proud of youuu sayanggg <3",
  "Semoga tahun ini menjadi tahun yang lebih baik dari tahun kemarin. Terdapat perubahan di diri kamu menjadi yang lebihhh baikkkk. Tapiii tidakk perlu dipaksakan yeahhhh, jika sedang capee sokk kamu bisa istirahat duluuuu, ngopi - ngopi duluu lalu kemudian lanjut lagii. Ohiyaaa kamuu juga bisa ceritaa ke aku lohhhh???? Ada orang yang bisaa nemenin kamuu saat susah atau senangg bubb yeyeyeye.",
  "Tetep jadii diri kamu yang saat ini ya sayang, tetap jadi orang baikk, tetap jadi orang yang sopan, tetap jadi orang yang spesial di mata aku.",
  "Happy birthday cantikkkkk, jadikann tahun ini melakukan hal - hal yang positif yaaaa, jadikan tahun ini menjadi orang yang lebih baikk lagiiii. Aku disini sebagai pacar kamu sangat mensupport kamu apapun yang kamu lakukan, apapun yang akan kamu lakukan, apapun yang udah kamu lakukann. Karena aku sangat sayang sama kamu, sangat - sangat merindukanmu hehehehe. I lovee you cantikkk",
  "Ohiyaaa itu dibawah ada tombol bub, kamu pencet aja. Kamu bisa menyampaikan apapun yang ingin kamu sampaikan, entah itu harapan kamu tahun ini mungkin atau apapun itu. Tapi aku bisa baca apapun yang kamu kirim bub. Nanti lepas kamu pencet tombol kirim jangan pencet apapun dulu sebelum sampe nanti ada pop up pesan udah ke kirim",
];
